### ISSUE TITLE
Support for Connect Tech BSPs

### ISSUE THREAD

**Issue by daniel-dsouza** [idavis/jetson-containers#4]
In order to have support for the Connecttech board support packages, you have to unzip a package over your Jetpack directory. I do not see an easy way to use the same process for docker approach.

How could I add Connecttech's BSP to the docker image?

[BSP documentation](http://connecttech.com/resource-center/cti-l4t-nvidia-jetson-board-support-package-release-notes/)

**Comment by idavis** [comment]
Sorry, I just saw this. I'll take a look at their BSPs. I wish I owned one to test, but I'll get back to you shortly.

**Comment by idavis** [comment]
@daniel-dsouza Take a look at the [feature/cti-bsp](https://github.com/idavis/jetson-containers/tree/feature/cti-bsp) branch. The flashing should work. There are some details in the base docker images that I have to figure out.

```bash
flash> make 32.1-cti-rogue
# or
flash> make 32.1-cti-rogue-imx274-2cam
# or
flash> make 32.1-cti-mimic-base
```

Plan for L4T base images:

```bash
flash> make l4t-32.1-cti-rogue
# or
flash> make l4t-32.1-cti-rogue-imx274-2cam
# or
flash> make l4t-32.1-cti-mimic-base
```

**Comment by idavis** [comment]
@daniel-dsouza I pushed an update which fixes the path for the base container. The image is so large due to the BSP's driver packages (1.36 GB).

**Comment by idavis** [comment]
@daniel-dsouza I've included all v124 and v203 based boards. Any chance you can test?

**Comment by daniel-dsouza** [comment]
@idavis I should be able to test the container today, and the flashing tomorrow when I have access to my carrier board again.

I have an astro board, so I'll be testing `astro-revG+`

**Comment by idavis** [comment]
Glad to hear @daniel-dsouza . Be sure to pull latest of the branch as I've updated it. This should be what you need:
 
Build the image:

```bash
# To build all v124 based flashing images:
~/jetson-containers$ make image-32.1-cti-v124
# To build astro-revG+ (gets tagged as astro-revGplus due to tag restrictions)
~/jetson-containers$ make make image-32.1-cti-v124-astro-revG+
# You'll eventually see (based on your .env file):
Successfully tagged l4t:32.1-cti-v124-astro-revGplus
```

Flash the image
```bash
~/jetson-containers$ ./flash/flash.sh l4t:32.1-cti-v124-astro-revGplus
```

**Comment by daniel-dsouza** [comment]
Swell! I was able to flash my astro board the docker container, and both Ethernet ports were correctly displayed. Looks like it works.

Do I still need Jetpack to install CUDA, or is there another build step I am missing?

**Comment by idavis** [comment]
I have an [introduction](https://codepyre.com/2019/07/jetson-containers-introduction/) blog post and [sample](https://codepyre.com/2019/07/jetson-containers-samples/) follow up. I haven't had a chance to lay out working with BSPs and carrier boards yet.

If you look at the `/docker/jetpack/4.2/tx2/base/Dockerfile`, you'll want to change:

```
ARG IMAGE_NAME
FROM ${IMAGE_NAME}:32.1-tx2
```
To point to your base image. Followed by what is done in the runtime image. With that, you can run just about anything in the samples. If you want cudnn, tensorrt, etc, then you'll need to layer in those like the devel images.

**Comment by idavis** [comment]
@daniel-dsouza As for your CUDA question, once you've flashed, you should be good to go. The device has the drivers, the container has the drivers and  libraries.

**Comment by daniel-dsouza** [comment]
Hmm. I keep getting an error

```
E: Unable to locate package cuda-cudart-10-0
E: Unable to locate package cuda-nvtx-10-0
The command '/bin/sh -c echo "5e3eedc3707305f9022d41754d6becde ${CUDA_TOOLKIT_PKG}" | md5sum -c - &&     dpkg --force-all -i ${CUDA_TOOLKIT_PKG} &&     rm ${CUDA_TOOLKIT_PKG} &&     apt-key add /var/cuda-repo-*-local*/*.pub &&     apt-get update &&     apt-get install -y --no-install-recommends --allow-downgrades cuda-cudart-10-0 cuda-nvtx-10-0 &&     ln -s cuda-10.0 /usr/local/cuda &&     dpkg --purge cuda-repo-l4t-10-0-local-10.0.166     &&     apt-get clean &&     rm -rf /var/lib/apt/lists/*' returned a non-zero code: 100
Makefile:150: recipe for target '32.1-tx2-jetpack-4.2-base' failed
make[1]: *** [32.1-tx2-jetpack-4.2-base] Error 100
make[1]: Leaving directory '/home/daniel/src/jetson-containers/docker/jetpack'
Makefile:69: recipe for target '32.1-tx2-jetpack-4.2' failed
make: *** [32.1-tx2-jetpack-4.2] Error 2
```

**Comment by idavis** [comment]
Can you post the output of `docker images | grep cti` and your Dockerfile contents? It sounds like the dependencies image isn't layered in.

**Comment by MartinYoungRovco** [comment]
I'm trying to do the same thing except I've got an elroy board with a TX2 module. I think I'm not understanding where the BSP handling fits into the rest of the system and I'm finding all the Makefiles and Dockerfiles a bit confusing.

First, I've got the BSP archive inside my dependencies image (l4t:tx2-jetpack-4.2.1-deps) and I can pull it in to docker builds using "COPY --from".

The suggested build commands in this issue don't work for me - it looks like the code's moved on since you wrote them so I've been trying to work out what I need to change.

Initially I tried to apply the BSP to the *-base image by adding steps in 32.2/tx2/Dockerfile but there's isn't a /Linux_for_Tegra directory at that point (the BSP install script insists on this). I think this is because it's the image being installed, not the image doing the installation. Is this right?

I see in the repo that there's a cti.Dockerfile used to build the image that does the flash which applies the BSP. It has a "/Linux_for_Tegra" directory at this point - is this the filesystem that's going to be flashed?

Am I right in now thinking that this the only place the BSP package needs applying? So I can build for generic TX2 and simply apply the BSP before the flash operation happens? The only new make targets that are needed are to make sure the right flashing image is build and used?

**Comment by idavis** [comment]
@MartinYoungRovco Thanks for pointing out a bug in the build scripts. Nvidia released JetPack 4.2.1 and I had to scramble as they changed a lot of how things worked. I just pushed the fixes to a branch and will merge shortly: https://github.com/idavis/jetson-containers/compare/feature/cti-bsp

I think the CTI BSP only needs to be applied at the flash level like you suggested, and I had it in the docker images for testing and didn't take it out yet as I couldn't test.

You shouldn't be using the 32.2 packages as they are for JetPack 4.2.1 which isn't supported by the CTI BSP. 

1. Make the flashing image inserting your exact Elroy package: elroy-mpcie elroy-mpcie-tx2i elroy-usb3 elroy-usb3-tx2i elroy-revF+ elroy-refF+-tx2i:
`make image-32.1-cti-v124-<replace>`
2. Then flash your device as above:
`~/jetson-containers$ ./flash/flash.sh l4t:32.1-cti-v124-<your device>`
3. Build the 32.1-tx2 L4T base
`~/jetson-containers$ make l4t-32.1-tx2`
4. Build the JetPack 4.2 tx2 images (see [this blog post](https://codepyre.com/2019/07/jetson-containers-introduction/) for detailed instructions for how this is put together). You can build all of this on your host machine and then [push the images directly to the device](https://codepyre.com/2019/07/pushing-images-to-devices/):
`~/jetson-containers$ make 32.1-tx2-jetpack-4.2`
5. I'd recommend [building the samples](https://codepyre.com/2019/07/jetson-containers-samples/) and then running it on your device to make sure everything is working correctly.

I'll let you know what I find out in my testing. I think I've answered your questions, but please let me know if I missed anything or if you have more.

**Comment by daniel-dsouza** [comment]
@idavis sorry I haven't responded recently, I've been running low on spare time that coincides with access to my tx2.

**Comment by idavis** [comment]
@daniel-dsouza @MartinYoungRovco I just flashed a CTI Orbitty with `~/jetson-containers$ ./flash/flash.sh l4t:32.1-cti-v124-orbitty` and I'm compiling the samples for `l4t-32.1-tx2-jetpack-4.2`. Once completed, I'll run them on the orbitty and make sure everything is working, and respond here.

**Comment by idavis** [comment]
The Orbitty is running accelerated with just the regular tx2 images and samples, but with the orbitty flashing and BSP application.

**Comment by idavis** [comment]
@daniel-dsouza @MartinYoungRovco I pushed pushed updated command line tasks and VS Code CTI support. So flash using the flashing containers stuff from this repo, which will apply the BSP from CTI, then build the regular JP 4.2 TX2 docker images and push them to the device.

**Comment by MartinYoungRovco** [comment]
Thanks for the speedy reply, it's very much appreciated.

I'm finding that, because I have DEPENDENCIES_IMAGE set, it's looking for cti.Docker file which doesn't (AFAICS) exist in the repo but I think I can probably synthesise this from tx2.Docker. [I wrote this prior to you most recent push.]

I have to stop now but will pull your changes and get back to it tomorrow.

Thanks!

**Comment by idavis** [comment]
Ah, that makes sense. The curl vs not was something I'm working through due to 4.2.1, which you don't need for CTI. I'll think about how to make this an easier pivot for which dockerfile to use. I hadn't found a clean way to embed the CTI BSP into a DEPS image, but I can automate downloading into its own deps image, or layering on top of the device deps. Just some thoughts to reflect on. Thanks for the feedback.

**Comment by MartinYoungRovco** [comment]
Yay! All working now. I've both reflashed the board and sent the samples images and run it. This is great.

I did this using your most recent push to master as per the instructions, except:

 - I put the CTI BSP archives in the same directory as the NVidia downloads so they end in my deps image so no extra layering.
 - I cloned flash/tx2.Dockerfile to flash/cti.Dockerfile and added a line to unpack the CTI BSP from the dependencies image (mostly copied from cti.curl.Dockerfile). I also had to remove the lines which install nvidia-docker2 because it needs a specific version of docker.io not present in a 4.2 image.
 - Flashing a 32.1/4.2 system using flash/cti.Dockerfile requires some files that one only gets from downloading the 32.2/4.2.1 Jetpack. "tensorrt.csv" is the first one it complains about. I chose to keep the 4.2.1 versions rather than modify the dockerfile.

Thanks for you work on this.

**Comment by idavis** [comment]
That's awesome @MartinYoungRovco .

Your workarounds make sense. The base needs to be 4.2 tx2, but the nvidia-docker2 and csv files are only for jetpack 4.2.1 and the 32.2 base. I would recommend not worrying about the nvdia-docker stuff as they mount the host file system into the container breaking the OS isolation.

 I meant to post yesterday, but I flashed the Orbitty with the 4.2 base and was running 4.2.1 tx2 containers with deepstream without issue.

I think I have an idea on how to make this smooth for CTI users. I'll try to have something for you soon.

**Comment by idavis** [comment]
@MartinYoungRovco @daniel-dsouza I'm [merging changes](https://github.com/idavis/jetson-containers/pull/13) tomorrow to make this a lot simpler:

Example: Building Orbitty, BSP version 125

```bash
>:~/jetson-containers/$ make cti-32.1-tx2-125-deps
>:~/jetson-containers/$ make 32.1-tx2-jetpack-4.2-deps
>:~/jetson-containers/$ make image-cti-32.1-v125-orbitty
>:~/jetson-containers/$ ./flash/flash.sh l4t:cti-32.1-v125-orbitty-image
```

**Comment by idavis** [comment]
@MartinYoungRovco @daniel-dsouza I've merged all of the updates I'm going to close this issue in two days unless I hear back from you that it isn't working. I was able to run DeepStream in a 4.2.1 container running on the 32.1 4.2 CTI base just fine as well.

**Comment by idavis** [comment]
Closed as no long an issue.

**Comment by daniel-dsouza** [comment]
Hello again @idavis  

I am trying to update the makefiles to support the 32.2 CTI BSPs. I have been able to build the astro G+ image again without Jetpack as before, but I cannot recall how to bundle the jetpack-devel libraries onto that image with the CTI BSPs.

**Comment by idavis** [comment]
@daniel-dsouza You shouldn't need to any more as I added support for [bsp dependency images](https://codepyre.com/2019/08/building-for-cti-devices/). I need to verify that the automated way for jetpack still works as I filed an issue with them on the latest SDK Manager.
